package com.mizusoft.hkeymap;

import android.app.Activity;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;

/**
 *
 * @author Tim
 */
public class KeySelectActivity extends Activity {

    public final static String KEY_CODE = "KEYCODE";
    private ListView listView;
    private ArrayAdapter<String> adapter;
    private final static String[] eventCode = new String[]{
        "KEYCODE_0",
        "KEYCODE_1",
        "KEYCODE_2",
        "KEYCODE_3",
        "KEYCODE_3D_MODE",
        "KEYCODE_4",
        "KEYCODE_5",
        "KEYCODE_6",
        "KEYCODE_7",
        "KEYCODE_8",
        "KEYCODE_9",
        "KEYCODE_A",
        "KEYCODE_ALT_LEFT",
        "KEYCODE_ALT_RIGHT",
        "KEYCODE_APOSTROPHE",
        "KEYCODE_APP_SWITCH",
        "KEYCODE_ASSIST",
        "KEYCODE_AT",
        "KEYCODE_AVR_INPUT",
        "KEYCODE_AVR_POWER",
        "KEYCODE_B",
        "KEYCODE_BACK",
        "KEYCODE_BACKSLASH",
        "KEYCODE_BOOKMARK",
        "KEYCODE_BREAK",
        "KEYCODE_BRIGHTNESS_DOWN",
        "KEYCODE_BRIGHTNESS_UP",
        "KEYCODE_BUTTON_1",
        "KEYCODE_BUTTON_10",
        "KEYCODE_BUTTON_11",
        "KEYCODE_BUTTON_12",
        "KEYCODE_BUTTON_13",
        "KEYCODE_BUTTON_14",
        "KEYCODE_BUTTON_15",
        "KEYCODE_BUTTON_16",
        "KEYCODE_BUTTON_2",
        "KEYCODE_BUTTON_3",
        "KEYCODE_BUTTON_4",
        "KEYCODE_BUTTON_5",
        "KEYCODE_BUTTON_6",
        "KEYCODE_BUTTON_7",
        "KEYCODE_BUTTON_8",
        "KEYCODE_BUTTON_9",
        "KEYCODE_BUTTON_A",
        "KEYCODE_BUTTON_B",
        "KEYCODE_BUTTON_C",
        "KEYCODE_BUTTON_L1",
        "KEYCODE_BUTTON_L2",
        "KEYCODE_BUTTON_MODE",
        "KEYCODE_BUTTON_R1",
        "KEYCODE_BUTTON_R2",
        "KEYCODE_BUTTON_SELECT",
        "KEYCODE_BUTTON_START",
        "KEYCODE_BUTTON_THUMBL",
        "KEYCODE_BUTTON_THUMBR",
        "KEYCODE_BUTTON_X",
        "KEYCODE_BUTTON_Y",
        "KEYCODE_BUTTON_Z",
        "KEYCODE_C",
        "KEYCODE_CALCULATOR",
        "KEYCODE_CALENDAR",
        "KEYCODE_CALL",
        "KEYCODE_CAMERA",
        "KEYCODE_CAPS_LOCK",
        "KEYCODE_CAPTIONS",
        "KEYCODE_CHANNEL_DOWN",
        "KEYCODE_CHANNEL_UP",
        "KEYCODE_CLEAR",
        "KEYCODE_COMMA",
        "KEYCODE_CONTACTS",
        "KEYCODE_CTRL_LEFT",
        "KEYCODE_CTRL_RIGHT",
        "KEYCODE_D",
        "KEYCODE_DEL",
        "KEYCODE_DPAD_CENTER",
        "KEYCODE_DPAD_DOWN",
        "KEYCODE_DPAD_LEFT",
        "KEYCODE_DPAD_RIGHT",
        "KEYCODE_DPAD_UP",
        "KEYCODE_DVR",
        "KEYCODE_E",
        "KEYCODE_EISU",
        "KEYCODE_ENDCALL",
        "KEYCODE_ENTER",
        "KEYCODE_ENVELOPE",
        "KEYCODE_EQUALS",
        "KEYCODE_ESCAPE",
        "KEYCODE_EXPLORER",
        "KEYCODE_F",
        "KEYCODE_F1",
        "KEYCODE_F10",
        "KEYCODE_F11",
        "KEYCODE_F12",
        "KEYCODE_F2",
        "KEYCODE_F3",
        "KEYCODE_F4",
        "KEYCODE_F5",
        "KEYCODE_F6",
        "KEYCODE_F7",
        "KEYCODE_F8",
        "KEYCODE_F9",
        "KEYCODE_FOCUS",
        "KEYCODE_FORWARD",
        "KEYCODE_FORWARD_DEL",
        "KEYCODE_FUNCTION",
        "KEYCODE_G",
        "KEYCODE_GRAVE",
        "KEYCODE_GUIDE",
        "KEYCODE_H",
        "KEYCODE_HEADSETHOOK",
        "KEYCODE_HENKAN",
        "KEYCODE_HOME",
        "KEYCODE_I",
        "KEYCODE_INFO",
        "KEYCODE_INSERT",
        "KEYCODE_J",
        "KEYCODE_K",
        "KEYCODE_KANA",
        "KEYCODE_KATAKANA_HIRAGANA",
        "KEYCODE_L",
        "KEYCODE_LANGUAGE_SWITCH",
        "KEYCODE_LEFT_BRACKET",
        "KEYCODE_M",
        "KEYCODE_MANNER_MODE",
        "KEYCODE_MEDIA_AUDIO_TRACK",
        "KEYCODE_MEDIA_CLOSE",
        "KEYCODE_MEDIA_EJECT",
        "KEYCODE_MEDIA_FAST_FORWARD",
        "KEYCODE_MEDIA_NEXT",
        "KEYCODE_MEDIA_PAUSE",
        "KEYCODE_MEDIA_PLAY",
        "KEYCODE_MEDIA_PLAY_PAUSE",
        "KEYCODE_MEDIA_PREVIOUS",
        "KEYCODE_MEDIA_RECORD",
        "KEYCODE_MEDIA_REWIND",
        "KEYCODE_MEDIA_STOP",
        "KEYCODE_MENU",
        "KEYCODE_META_LEFT",
        "KEYCODE_META_RIGHT",
        "KEYCODE_MINUS",
        "KEYCODE_MOVE_END",
        "KEYCODE_MOVE_HOME",
        "KEYCODE_MUHENKAN",
        "KEYCODE_MUSIC",
        "KEYCODE_MUTE",
        "KEYCODE_N",
        "KEYCODE_NOTIFICATION",
        "KEYCODE_NUM",
        "KEYCODE_NUMPAD_0",
        "KEYCODE_NUMPAD_1",
        "KEYCODE_NUMPAD_2",
        "KEYCODE_NUMPAD_3",
        "KEYCODE_NUMPAD_4",
        "KEYCODE_NUMPAD_5",
        "KEYCODE_NUMPAD_6",
        "KEYCODE_NUMPAD_7",
        "KEYCODE_NUMPAD_8",
        "KEYCODE_NUMPAD_9",
        "KEYCODE_NUMPAD_ADD",
        "KEYCODE_NUMPAD_COMMA",
        "KEYCODE_NUMPAD_DIVIDE",
        "KEYCODE_NUMPAD_DOT",
        "KEYCODE_NUMPAD_ENTER",
        "KEYCODE_NUMPAD_EQUALS",
        "KEYCODE_NUMPAD_LEFT_PAREN",
        "KEYCODE_NUMPAD_MULTIPLY",
        "KEYCODE_NUMPAD_RIGHT_PAREN",
        "KEYCODE_NUMPAD_SUBTRACT",
        "KEYCODE_NUM_LOCK",
        "KEYCODE_O",
        "KEYCODE_P",
        "KEYCODE_PAGE_DOWN",
        "KEYCODE_PAGE_UP",
        "KEYCODE_PERIOD",
        "KEYCODE_PICTSYMBOLS",
        "KEYCODE_PLUS",
        "KEYCODE_POUND",
        "KEYCODE_POWER",
        "KEYCODE_PROG_BLUE",
        "KEYCODE_PROG_GREEN",
        "KEYCODE_PROG_RED",
        "KEYCODE_PROG_YELLOW",
        "KEYCODE_Q",
        "KEYCODE_R",
        "KEYCODE_RIGHT_BRACKET",
        "KEYCODE_RO",
        "KEYCODE_S",
        "KEYCODE_SCROLL_LOCK",
        "KEYCODE_SEARCH",
        "KEYCODE_SEMICOLON",
        "KEYCODE_SETTINGS",
        "KEYCODE_SHIFT_LEFT",
        "KEYCODE_SHIFT_RIGHT",
        "KEYCODE_SLASH",
        "KEYCODE_SOFT_LEFT",
        "KEYCODE_SOFT_RIGHT",
        "KEYCODE_SPACE",
        "KEYCODE_STAR",
        "KEYCODE_STB_INPUT",
        "KEYCODE_STB_POWER",
        "KEYCODE_SWITCH_CHARSET",
        "KEYCODE_SYM",
        "KEYCODE_SYSRQ",
        "KEYCODE_T",
        "KEYCODE_TAB",
        "KEYCODE_TV",
        "KEYCODE_TV_INPUT",
        "KEYCODE_TV_POWER",
        "KEYCODE_U",
        "KEYCODE_UNKNOWN",
        "KEYCODE_V",
        "KEYCODE_VOLUME_DOWN",
        "KEYCODE_VOLUME_MUTE",
        "KEYCODE_VOLUME_UP",
        "KEYCODE_W",
        "KEYCODE_WINDOW",
        "KEYCODE_X",
        "KEYCODE_Y",
        "KEYCODE_YEN",
        "KEYCODE_Z",
        "KEYCODE_ZENKAKU_HANKAKU",
        "KEYCODE_ZOOM_IN",
        "KEYCODE_ZOOM_OUT"};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.key);
        this.listView = (ListView) findViewById(R.id.keylist);
        this.adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, android.R.id.text1, eventCode);
        this.listView.setAdapter(adapter);
        this.listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> av, View view, int i, long l) {
                setResult(Activity.RESULT_OK, getIntent().putExtra(KEY_CODE, adapter.getItem(i)));
                finish();
            }
        });
    }

}
